/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Library {
    val valueAtSpecificTag : String = "experiment/2_tag_modified"

    fun someLibraryMethod(): Boolean {
        return true
    }
}
